;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        fdx/indent-this-and-previous
        ))

(setq mc/cmds-to-run-once
      '(
        ))
